# Generated by Django 4.2.27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_days',
            field=models.CharField(
                blank=True,
                help_text='Например: 3 дня',
                max_length=50,
                verbose_name='Срок доставки при отсутствии',
            ),
        ),
    ]
